// Path: src/utils/attributions.tsx
// This file is automatically generated by scripts/attributions.js
// Do not edit this file manually, it will be overwritten

export const attributions = [
    {
        name: 'Adobe Source Sans 3',
        version: '3.046',
        url: 'https://github.com/adobe-fonts/source-sans',
        license: 'OFL-1.1'
    },
    {
        name: 'Rubik Filtered',
        version: '1.0',
        url: 'https://github.com/NaN-xyz/Rubik-Filtered',
        license: 'OFL-1.1'
    },
    {
        name: '@ampproject/remapping@2.2.0',
        license: 'Apache-2.0',
        url: 'https://github.com/ampproject/remapping'
    },
    {
        name: '@astrojs/compiler@0.31.4',
        license: 'MIT',
        url: 'https://github.com/withastro/compiler'
    },
    {
        name: '@astrojs/compiler@1.0.1',
        license: 'MIT',
        url: 'https://github.com/withastro/compiler'
    },
    {
        name: '@astrojs/language-server@0.28.3',
        license: 'MIT',
        url: 'https://github.com/'
    },
    {
        name: '@astrojs/markdown-remark@2.0.1',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@astrojs/prism@2.0.0',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@astrojs/react@2.0.2',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@astrojs/tailwind@3.0.1',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@astrojs/telemetry@2.0.0',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@astrojs/webapi@2.0.0',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: '@babel/code-frame@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/compat-data@7.20.10',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/core@7.20.12',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/generator@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-annotate-as-pure@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-compilation-targets@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-environment-visitor@7.18.9',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-function-name@7.19.0',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-hoist-variables@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-module-imports@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-module-transforms@7.20.11',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-plugin-utils@7.20.2',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-simple-access@7.20.2',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-split-export-declaration@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-string-parser@7.19.4',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-validator-identifier@7.19.1',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helper-validator-option@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/helpers@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/highlight@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/parser@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/plugin-syntax-jsx@7.18.6',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/plugin-transform-react-jsx@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/template@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/traverse@7.20.12',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@babel/types@7.20.7',
        license: 'MIT',
        url: 'https://github.com/babel/babel'
    },
    {
        name: '@emmetio/abbreviation@2.2.3',
        license: 'MIT',
        url: 'https://github.com/emmetio/emmet'
    },
    {
        name: '@emmetio/css-abbreviation@2.1.4',
        license: 'MIT',
        url: 'https://github.com/emmetio/emmet'
    },
    {
        name: '@emmetio/scanner@1.0.0',
        license: 'MIT',
        url: 'https://github.com/emmetio/stream-reader'
    },
    {
        name: '@esbuild/darwin-x64@0.16.17',
        license: 'MIT',
        url: 'https://github.com/evanw/esbuild'
    },
    {
        name: '@eslint/eslintrc@1.4.1',
        license: 'MIT',
        url: 'https://github.com/eslint/eslintrc'
    },
    {
        name: '@humanwhocodes/config-array@0.11.8',
        license: 'Apache-2.0',
        url: 'https://github.com/humanwhocodes/config-array'
    },
    {
        name: '@humanwhocodes/module-importer@1.0.1',
        license: 'Apache-2.0',
        url: 'https://github.com/humanwhocodes/module-importer'
    },
    {
        name: '@humanwhocodes/object-schema@1.2.1',
        license: 'BSD-3-Clause',
        url: 'https://github.com/humanwhocodes/object-schema'
    },
    {
        name: '@jridgewell/gen-mapping@0.1.1',
        license: 'MIT',
        url: 'https://github.com/jridgewell/gen-mapping'
    },
    {
        name: '@jridgewell/gen-mapping@0.3.2',
        license: 'MIT',
        url: 'https://github.com/jridgewell/gen-mapping'
    },
    {
        name: '@jridgewell/resolve-uri@3.1.0',
        license: 'MIT',
        url: 'https://github.com/jridgewell/resolve-uri'
    },
    {
        name: '@jridgewell/set-array@1.1.2',
        license: 'MIT',
        url: 'https://github.com/jridgewell/set-array'
    },
    {
        name: '@jridgewell/sourcemap-codec@1.4.14',
        license: 'MIT',
        url: 'https://github.com/jridgewell/sourcemap-codec'
    },
    {
        name: '@jridgewell/trace-mapping@0.3.17',
        license: 'MIT',
        url: 'https://github.com/jridgewell/trace-mapping'
    },
    {
        name: '@ljharb/has-package-exports-patterns@0.0.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-package-exports'
    },
    {
        name: '@nodelib/fs.scandir@2.1.5',
        license: 'MIT',
        url: 'https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.scandir'
    },
    {
        name: '@nodelib/fs.stat@2.0.5',
        license: 'MIT',
        url: 'https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.stat'
    },
    {
        name: '@nodelib/fs.walk@1.2.8',
        license: 'MIT',
        url: 'https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.walk'
    },
    {
        name: '@pkgr/utils@2.3.1',
        license: 'MIT',
        url: 'https://github.com/un-ts/pkgr'
    },
    {
        name: '@proload/core@0.3.3',
        license: 'MIT',
        url: 'https://github.com/natemoo-re/proload'
    },
    {
        name: '@tootallnate/once@2.0.0',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/once'
    },
    {
        name: '@types/babel__core@7.1.20',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/babel__generator@7.6.4',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/babel__template@7.4.1',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/babel__traverse@7.18.3',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/debug@4.1.7',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/hast@2.3.4',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/json-schema@7.0.11',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/json5@0.0.30',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/mdast@3.0.10',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/ms@0.7.31',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/nlcst@1.0.0',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/parse5@6.0.3',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/prop-types@15.7.5',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/react-dom@18.0.10',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/react@18.0.26',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/resolve@1.20.2',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/scheduler@0.16.2',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/semver@7.3.13',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/unist@2.0.6',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@types/yargs-parser@21.0.0',
        license: 'MIT',
        url: 'https://github.com/DefinitelyTyped/DefinitelyTyped'
    },
    {
        name: '@typescript-eslint/eslint-plugin@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/parser@5.48.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/scope-manager@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/type-utils@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/types@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/typescript-estree@5.48.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/utils@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@typescript-eslint/visitor-keys@5.48.1',
        license: 'MIT',
        url: 'https://github.com/typescript-eslint/typescript-eslint'
    },
    {
        name: '@vscode/emmet-helper@2.8.6',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-emmet-helper'
    },
    {
        name: '@vscode/l10n@0.0.10',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-l10n'
    },
    {
        name: 'abab@2.0.6',
        license: 'BSD-3-Clause',
        url: 'https://github.com/jsdom/abab'
    },
    {
        name: 'abbrev@1.1.1',
        license: 'ISC',
        url: 'https://github.com/isaacs/abbrev-js'
    },
    {
        name: 'acorn-globals@7.0.1',
        license: 'MIT',
        url: 'https://github.com/ForbesLindesay/acorn-globals'
    },
    {
        name: 'acorn-jsx@5.3.2',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn-jsx'
    },
    {
        name: 'acorn-node@1.8.2',
        license: 'Apache-2.0',
        url: 'https://github.com/browserify/acorn-node'
    },
    {
        name: 'acorn-walk@7.2.0',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn'
    },
    {
        name: 'acorn-walk@8.2.0',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn'
    },
    {
        name: 'acorn@7.4.1',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn'
    },
    {
        name: 'acorn@8.8.1',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn'
    },
    {
        name: 'acorn@8.8.2',
        license: 'MIT',
        url: 'https://github.com/acornjs/acorn'
    },
    {
        name: 'agent-base@6.0.2',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/node-agent-base'
    },
    {
        name: 'ajv@6.12.6',
        license: 'MIT',
        url: 'https://github.com/ajv-validator/ajv'
    },
    {
        name: 'ansi-align@3.0.1',
        license: 'ISC',
        url: 'https://github.com/nexdrew/ansi-align'
    },
    {
        name: 'ansi-escapes@6.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/ansi-escapes'
    },
    {
        name: 'ansi-regex@5.0.1',
        license: 'MIT',
        url: 'https://github.com/chalk/ansi-regex'
    },
    {
        name: 'ansi-regex@6.0.1',
        license: 'MIT',
        url: 'https://github.com/chalk/ansi-regex'
    },
    {
        name: 'ansi-styles@3.2.1',
        license: 'MIT',
        url: 'https://github.com/chalk/ansi-styles'
    },
    {
        name: 'ansi-styles@4.3.0',
        license: 'MIT',
        url: 'https://github.com/chalk/ansi-styles'
    },
    {
        name: 'ansi-styles@6.2.1',
        license: 'MIT',
        url: 'https://github.com/chalk/ansi-styles'
    },
    {
        name: 'anymatch@3.1.3',
        license: 'ISC',
        url: 'https://github.com/micromatch/anymatch'
    },
    {
        name: 'arg@5.0.2',
        license: 'MIT',
        url: 'https://github.com/vercel/arg'
    },
    {
        name: 'argparse@1.0.10',
        license: 'MIT',
        url: 'https://github.com/nodeca/argparse'
    },
    {
        name: 'argparse@2.0.1',
        license: 'Python-2.0',
        url: 'https://github.com/nodeca/argparse'
    },
    {
        name: 'array-find-index@1.0.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/array-find-index'
    },
    {
        name: 'array-includes@3.1.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/array-includes'
    },
    {
        name: 'array-iterate@2.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/array-iterate'
    },
    {
        name: 'array-union@2.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/array-union'
    },
    {
        name: 'array.prototype.flatmap@1.3.1',
        license: 'MIT',
        url: 'https://github.com/es-shims/Array.prototype.flatMap'
    },
    {
        name: 'array.prototype.tosorted@1.1.1',
        license: 'MIT',
        url: 'https://github.com/es-shims/Array.prototype.toSorted'
    },
    {
        name: 'asap@2.0.6',
        license: 'MIT',
        url: 'https://github.com/kriskowal/asap'
    },
    {
        name: 'astro@2.0.5',
        license: 'MIT',
        url: 'https://github.com/withastro/astro'
    },
    {
        name: 'asynckit@0.4.0',
        license: 'MIT',
        url: 'https://github.com/alexindigo/asynckit'
    },
    {
        name: 'autoprefixer@10.4.13',
        license: 'MIT',
        url: 'https://github.com/postcss/autoprefixer'
    },
    {
        name: 'available-typed-arrays@1.0.5',
        license: 'MIT',
        url: 'https://github.com/inspect-js/available-typed-arrays'
    },
    {
        name: 'bail@2.0.2',
        license: 'MIT',
        url: 'https://github.com/wooorm/bail'
    },
    {
        name: 'balanced-match@1.0.2',
        license: 'MIT',
        url: 'https://github.com/juliangruber/balanced-match'
    },
    {
        name: 'base64-js@1.5.1',
        license: 'MIT',
        url: 'https://github.com/beatgammit/base64-js'
    },
    {
        name: 'binary-extensions@2.2.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/binary-extensions'
    },
    {
        name: 'bl@5.1.0',
        license: 'MIT',
        url: 'https://github.com/rvagg/bl'
    },
    {
        name: 'boxen@6.2.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/boxen'
    },
    {
        name: 'brace-expansion@1.1.11',
        license: 'MIT',
        url: 'https://github.com/juliangruber/brace-expansion'
    },
    {
        name: 'braces@3.0.2',
        license: 'MIT',
        url: 'https://github.com/micromatch/braces'
    },
    {
        name: 'browserslist@4.21.4',
        license: 'MIT',
        url: 'https://github.com/browserslist/browserslist'
    },
    {
        name: 'buffer@6.0.3',
        license: 'MIT',
        url: 'https://github.com/feross/buffer'
    },
    {
        name: 'busboy@1.6.0',
        license: 'MIT',
        url: 'https://github.com/mscdex/busboy'
    },
    {
        name: 'call-bind@1.0.2',
        license: 'MIT',
        url: 'https://github.com/ljharb/call-bind'
    },
    {
        name: 'callsites@3.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/callsites'
    },
    {
        name: 'camelcase-css@2.0.1',
        license: 'MIT',
        url: 'https://github.com/stevenvachon/camelcase-css'
    },
    {
        name: 'camelcase@6.3.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/camelcase'
    },
    {
        name: 'caniuse-lite@1.0.30001442',
        license: 'CC-BY-4.0',
        url: 'https://github.com/browserslist/caniuse-lite'
    },
    {
        name: 'ccount@2.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/ccount'
    },
    {
        name: 'chalk@2.4.2',
        license: 'MIT',
        url: 'https://github.com/chalk/chalk'
    },
    {
        name: 'chalk@4.1.2',
        license: 'MIT',
        url: 'https://github.com/chalk/chalk'
    },
    {
        name: 'chalk@5.2.0',
        license: 'MIT',
        url: 'https://github.com/chalk/chalk'
    },
    {
        name: 'character-entities-html4@2.1.0',
        license: 'MIT',
        url: 'https://github.com/wooorm/character-entities-html4'
    },
    {
        name: 'character-entities-legacy@3.0.0',
        license: 'MIT',
        url: 'https://github.com/wooorm/character-entities-legacy'
    },
    {
        name: 'character-entities@2.0.2',
        license: 'MIT',
        url: 'https://github.com/wooorm/character-entities'
    },
    {
        name: 'chardet@0.7.0',
        license: 'MIT',
        url: 'https://github.com/runk/node-chardet'
    },
    {
        name: 'chokidar@3.5.3',
        license: 'MIT',
        url: 'https://github.com/paulmillr/chokidar'
    },
    {
        name: 'ci-info@3.7.1',
        license: 'MIT',
        url: 'https://github.com/watson/ci-info'
    },
    {
        name: 'cli-boxes@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/cli-boxes'
    },
    {
        name: 'cli-cursor@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/cli-cursor'
    },
    {
        name: 'cli-spinners@2.7.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/cli-spinners'
    },
    {
        name: 'cli-width@4.0.0',
        license: 'ISC',
        url: 'https://github.com/knownasilya/cli-width'
    },
    {
        name: 'clone@1.0.4',
        license: 'MIT',
        url: 'https://github.com/pvorb/node-clone'
    },
    {
        name: 'color-convert@1.9.3',
        license: 'MIT',
        url: 'https://github.com/Qix-/color-convert'
    },
    {
        name: 'color-convert@2.0.1',
        license: 'MIT',
        url: 'https://github.com/Qix-/color-convert'
    },
    {
        name: 'color-name@1.1.3',
        license: 'MIT',
        url: 'https://github.com/dfcreative/color-name'
    },
    {
        name: 'color-name@1.1.4',
        license: 'MIT',
        url: 'https://github.com/colorjs/color-name'
    },
    {
        name: 'combined-stream@1.0.8',
        license: 'MIT',
        url: 'https://github.com/felixge/node-combined-stream'
    },
    {
        name: 'comma-separated-tokens@2.0.3',
        license: 'MIT',
        url: 'https://github.com/wooorm/comma-separated-tokens'
    },
    {
        name: 'common-ancestor-path@1.0.1',
        license: 'ISC',
        url: 'https://github.com/isaacs/common-ancestor-path'
    },
    {
        name: 'concat-map@0.0.1',
        license: 'MIT',
        url: 'https://github.com/substack/node-concat-map'
    },
    {
        name: 'convert-source-map@1.9.0',
        license: 'MIT',
        url: 'https://github.com/thlorenz/convert-source-map'
    },
    {
        name: 'cookie@0.5.0',
        license: 'MIT',
        url: 'https://github.com/jshttp/cookie'
    },
    {
        name: 'cross-spawn@7.0.3',
        license: 'MIT',
        url: 'https://github.com/moxystudio/node-cross-spawn'
    },
    {
        name: 'cssesc@3.0.0',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/cssesc'
    },
    {
        name: 'cssom@0.3.8',
        license: 'MIT',
        url: 'https://github.com/NV/CSSOM'
    },
    {
        name: 'cssom@0.5.0',
        license: 'MIT',
        url: 'https://github.com/NV/CSSOM'
    },
    {
        name: 'cssstyle@2.3.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/cssstyle'
    },
    {
        name: 'csstype@3.1.1',
        license: 'MIT',
        url: 'https://github.com/frenic/csstype'
    },
    {
        name: 'data-uri-to-buffer@4.0.0',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/node-data-uri-to-buffer'
    },
    {
        name: 'data-urls@3.0.2',
        license: 'MIT',
        url: 'https://github.com/jsdom/data-urls'
    },
    {
        name: 'debug@3.2.7',
        license: 'MIT',
        url: 'https://github.com/visionmedia/debug'
    },
    {
        name: 'debug@4.3.4',
        license: 'MIT',
        url: 'https://github.com/debug-js/debug'
    },
    {
        name: 'debuglog@1.0.1',
        license: 'MIT',
        url: 'https://github.com/sam-github/node-debuglog'
    },
    {
        name: 'decimal.js@10.4.3',
        license: 'MIT',
        url: 'https://github.com/MikeMcl/decimal.js'
    },
    {
        name: 'decode-named-character-reference@1.0.2',
        license: 'MIT',
        url: 'https://github.com/wooorm/decode-named-character-reference'
    },
    {
        name: 'deep-is@0.1.4',
        license: 'MIT',
        url: 'https://github.com/thlorenz/deep-is'
    },
    {
        name: 'deepmerge-ts@4.2.2',
        license: 'BSD-3-Clause',
        url: 'https://github.com/RebeccaStevens/deepmerge-ts'
    },
    {
        name: 'deepmerge@4.2.2',
        license: 'MIT',
        url: 'https://github.com/TehShrike/deepmerge'
    },
    {
        name: 'defaults@1.0.4',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/node-defaults'
    },
    {
        name: 'define-lazy-prop@2.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/define-lazy-prop'
    },
    {
        name: 'define-properties@1.1.4',
        license: 'MIT',
        url: 'https://github.com/ljharb/define-properties'
    },
    {
        name: 'defined@1.0.1',
        license: 'MIT',
        url: 'https://github.com/inspect-js/defined'
    },
    {
        name: 'delayed-stream@1.0.0',
        license: 'MIT',
        url: 'https://github.com/felixge/node-delayed-stream'
    },
    {
        name: 'dequal@2.0.3',
        license: 'MIT',
        url: 'https://github.com/lukeed/dequal'
    },
    {
        name: 'detective@5.2.1',
        license: 'MIT',
        url: 'https://github.com/browserify/detective'
    },
    {
        name: 'devalue@4.2.1',
        license: 'MIT',
        url: 'https://github.com/Rich-Harris/devalue'
    },
    {
        name: 'dezalgo@1.0.4',
        license: 'ISC',
        url: 'https://github.com/npm/dezalgo'
    },
    {
        name: 'didyoumean@1.2.2',
        license: 'Apache-2.0',
        url: 'https://github.com/dcporter/didyoumean.js'
    },
    {
        name: 'diff@5.1.0',
        license: 'BSD-3-Clause',
        url: 'https://github.com/kpdecker/jsdiff'
    },
    {
        name: 'dir-glob@3.0.1',
        license: 'MIT',
        url: 'https://github.com/kevva/dir-glob'
    },
    {
        name: 'dlv@1.1.3',
        license: 'MIT',
        url: 'https://github.com/developit/dlv'
    },
    {
        name: 'doctrine@2.1.0',
        license: 'Apache-2.0',
        url: 'https://github.com/eslint/doctrine'
    },
    {
        name: 'doctrine@3.0.0',
        license: 'Apache-2.0',
        url: 'https://github.com/eslint/doctrine'
    },
    {
        name: 'domexception@4.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/domexception'
    },
    {
        name: 'dotenv@16.0.3',
        license: 'BSD-2-Clause',
        url: 'https://github.com/motdotla/dotenv'
    },
    {
        name: 'dset@3.1.2',
        license: 'MIT',
        url: 'https://github.com/lukeed/dset'
    },
    {
        name: 'eastasianwidth@0.2.0',
        license: 'MIT',
        url: 'https://github.com/komagata/eastasianwidth'
    },
    {
        name: 'electron-to-chromium@1.4.284',
        license: 'ISC',
        url: 'https://github.com/kilian/electron-to-chromium'
    },
    {
        name: 'emmet@2.3.6',
        license: 'MIT',
        url: 'https://github.com/emmetio/emmet'
    },
    {
        name: 'emoji-regex@8.0.0',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/emoji-regex'
    },
    {
        name: 'emoji-regex@9.2.2',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/emoji-regex'
    },
    {
        name: 'entities@4.4.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/fb55/entities'
    },
    {
        name: 'es-abstract@1.21.1',
        license: 'MIT',
        url: 'https://github.com/ljharb/es-abstract'
    },
    {
        name: 'es-module-lexer@1.1.0',
        license: 'MIT',
        url: 'https://github.com/guybedford/es-module-lexer'
    },
    {
        name: 'es-set-tostringtag@2.0.1',
        license: 'MIT',
        url: 'https://github.com/es-shims/es-set-tostringtag'
    },
    {
        name: 'es-shim-unscopables@1.0.0',
        license: 'MIT',
        url: 'https://github.com/ljharb/es-shim-unscopables'
    },
    {
        name: 'es-to-primitive@1.2.1',
        license: 'MIT',
        url: 'https://github.com/ljharb/es-to-primitive'
    },
    {
        name: 'esbuild@0.16.17',
        license: 'MIT',
        url: 'https://github.com/evanw/esbuild'
    },
    {
        name: 'escalade@3.1.1',
        license: 'MIT',
        url: 'https://github.com/lukeed/escalade'
    },
    {
        name: 'escape-string-regexp@1.0.5',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/escape-string-regexp'
    },
    {
        name: 'escape-string-regexp@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/escape-string-regexp'
    },
    {
        name: 'escape-string-regexp@5.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/escape-string-regexp'
    },
    {
        name: 'escodegen@2.0.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/estools/escodegen'
    },
    {
        name: 'eslint-plugin-prettier@4.2.1',
        license: 'MIT',
        url: 'https://github.com/prettier/eslint-plugin-prettier'
    },
    {
        name: 'eslint-plugin-react@7.32.0',
        license: 'MIT',
        url: 'https://github.com/jsx-eslint/eslint-plugin-react'
    },
    {
        name: 'eslint-scope@5.1.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/eslint/eslint-scope'
    },
    {
        name: 'eslint-scope@7.1.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/eslint/eslint-scope'
    },
    {
        name: 'eslint-utils@3.0.0',
        license: 'MIT',
        url: 'https://github.com/mysticatea/eslint-utils'
    },
    {
        name: 'eslint-visitor-keys@2.1.0',
        license: 'Apache-2.0',
        url: 'https://github.com/eslint/eslint-visitor-keys'
    },
    {
        name: 'eslint-visitor-keys@3.3.0',
        license: 'Apache-2.0',
        url: 'https://github.com/eslint/eslint-visitor-keys'
    },
    {
        name: 'eslint@8.31.0',
        license: 'MIT',
        url: 'https://github.com/eslint/eslint'
    },
    {
        name: 'espree@9.4.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/eslint/espree'
    },
    {
        name: 'esprima@4.0.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/jquery/esprima'
    },
    {
        name: 'esquery@1.4.0',
        license: 'BSD-3-Clause',
        url: 'https://github.com/estools/esquery'
    },
    {
        name: 'esrecurse@4.3.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/estools/esrecurse'
    },
    {
        name: 'estraverse@4.3.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/estools/estraverse'
    },
    {
        name: 'estraverse@5.3.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/estools/estraverse'
    },
    {
        name: 'estree-walker@3.0.2',
        license: 'MIT',
        url: 'https://github.com/Rich-Harris/estree-walker'
    },
    {
        name: 'esutils@2.0.3',
        license: 'BSD-2-Clause',
        url: 'https://github.com/estools/esutils'
    },
    {
        name: 'events@3.3.0',
        license: 'MIT',
        url: 'https://github.com/Gozala/events'
    },
    {
        name: 'execa@6.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/execa'
    },
    {
        name: 'extend-shallow@2.0.1',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/extend-shallow'
    },
    {
        name: 'extend@3.0.2',
        license: 'MIT',
        url: 'https://github.com/justmoon/node-extend'
    },
    {
        name: 'external-editor@3.1.0',
        license: 'MIT',
        url: 'https://github.com/mrkmg/node-external-editor'
    },
    {
        name: 'fast-deep-equal@3.1.3',
        license: 'MIT',
        url: 'https://github.com/epoberezkin/fast-deep-equal'
    },
    {
        name: 'fast-diff@1.2.0',
        license: 'Apache-2.0',
        url: 'https://github.com/jhchen/fast-diff'
    },
    {
        name: 'fast-glob@3.2.12',
        license: 'MIT',
        url: 'https://github.com/mrmlnc/fast-glob'
    },
    {
        name: 'fast-json-stable-stringify@2.1.0',
        license: 'MIT',
        url: 'https://github.com/epoberezkin/fast-json-stable-stringify'
    },
    {
        name: 'fast-levenshtein@2.0.6',
        license: 'MIT',
        url: 'https://github.com/hiddentao/fast-levenshtein'
    },
    {
        name: 'fastq@1.15.0',
        license: 'ISC',
        url: 'https://github.com/mcollina/fastq'
    },
    {
        name: 'fetch-blob@3.2.0',
        license: 'MIT',
        url: 'https://github.com/node-fetch/fetch-blob'
    },
    {
        name: 'figures@5.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/figures'
    },
    {
        name: 'file-entry-cache@6.0.1',
        license: 'MIT',
        url: 'https://github.com/royriojas/file-entry-cache'
    },
    {
        name: 'fill-range@7.0.1',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/fill-range'
    },
    {
        name: 'find-up@4.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/find-up'
    },
    {
        name: 'find-up@5.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/find-up'
    },
    {
        name: 'find-yarn-workspace-root2@1.2.16',
        license: 'Apache-2.0',
        url: 'https://github.com/bluelovers/find-yarn-workspace-root'
    },
    {
        name: 'flat-cache@3.0.4',
        license: 'MIT',
        url: 'https://github.com/royriojas/flat-cache'
    },
    {
        name: 'flatted@3.2.7',
        license: 'ISC',
        url: 'https://github.com/WebReflection/flatted'
    },
    {
        name: 'for-each@0.3.3',
        license: 'MIT',
        url: 'https://github.com/Raynos/for-each'
    },
    {
        name: 'form-data@4.0.0',
        license: 'MIT',
        url: 'https://github.com/form-data/form-data'
    },
    {
        name: 'formdata-polyfill@4.0.10',
        license: 'MIT',
        url: 'git+https://jimmywarting@github.com/jimmywarting/FormData'
    },
    {
        name: 'fraction.js@4.2.0',
        license: 'MIT',
        url: 'https://github.com/infusion/Fraction.js'
    },
    {
        name: 'fs.realpath@1.0.0',
        license: 'ISC',
        url: 'https://github.com/isaacs/fs.realpath'
    },
    {
        name: 'fsevents@2.3.2',
        license: 'MIT',
        url: 'https://github.com/fsevents/fsevents'
    },
    {
        name: 'function-bind@1.1.1',
        license: 'MIT',
        url: 'https://github.com/Raynos/function-bind'
    },
    {
        name: 'function.prototype.name@1.1.5',
        license: 'MIT',
        url: 'https://github.com/es-shims/Function.prototype.name'
    },
    {
        name: 'functions-have-names@1.2.3',
        license: 'MIT',
        url: 'https://github.com/inspect-js/functions-have-names'
    },
    {
        name: 'gensync@1.0.0-beta.2',
        license: 'MIT',
        url: 'https://github.com/loganfsmyth/gensync'
    },
    {
        name: 'get-intrinsic@1.1.3',
        license: 'MIT',
        url: 'https://github.com/ljharb/get-intrinsic'
    },
    {
        name: 'get-stream@6.0.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/get-stream'
    },
    {
        name: 'get-symbol-description@1.0.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/get-symbol-description'
    },
    {
        name: 'github-slugger@1.5.0',
        license: 'ISC',
        url: 'https://github.com/Flet/github-slugger'
    },
    {
        name: 'github-slugger@2.0.0',
        license: 'ISC',
        url: 'https://github.com/Flet/github-slugger'
    },
    {
        name: 'glob-parent@5.1.2',
        license: 'ISC',
        url: 'https://github.com/gulpjs/glob-parent'
    },
    {
        name: 'glob-parent@6.0.2',
        license: 'ISC',
        url: 'https://github.com/gulpjs/glob-parent'
    },
    {
        name: 'glob@7.2.3',
        license: 'ISC',
        url: 'https://github.com/isaacs/node-glob'
    },
    {
        name: 'globals@11.12.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/globals'
    },
    {
        name: 'globals@13.19.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/globals'
    },
    {
        name: 'globalthis@1.0.3',
        license: 'MIT',
        url: 'https://github.com/ljharb/System.global'
    },
    {
        name: 'globalyzer@0.1.0',
        license: 'MIT',
        url: 'https://github.com/terkelg/globalyzer'
    },
    {
        name: 'globby@11.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/globby'
    },
    {
        name: 'globrex@0.1.2',
        license: 'MIT',
        url: 'https://github.com/terkelg/globrex'
    },
    {
        name: 'gopd@1.0.1',
        license: 'MIT',
        url: 'https://github.com/ljharb/gopd'
    },
    {
        name: 'graceful-fs@4.2.10',
        license: 'ISC',
        url: 'https://github.com/isaacs/node-graceful-fs'
    },
    {
        name: 'grapheme-splitter@1.0.4',
        license: 'MIT',
        url: 'https://github.com/orling/grapheme-splitter'
    },
    {
        name: 'gray-matter@4.0.3',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/gray-matter'
    },
    {
        name: 'has-bigints@1.0.2',
        license: 'MIT',
        url: 'https://github.com/ljharb/has-bigints'
    },
    {
        name: 'has-flag@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/has-flag'
    },
    {
        name: 'has-flag@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/has-flag'
    },
    {
        name: 'has-package-exports@1.3.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-package-exports'
    },
    {
        name: 'has-property-descriptors@1.0.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-property-descriptors'
    },
    {
        name: 'has-proto@1.0.1',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-proto'
    },
    {
        name: 'has-symbols@1.0.3',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-symbols'
    },
    {
        name: 'has-tostringtag@1.0.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/has-tostringtag'
    },
    {
        name: 'has@1.0.3',
        license: 'MIT',
        url: 'https://github.com/tarruda/has'
    },
    {
        name: 'hast-to-hyperscript@10.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-to-hyperscript'
    },
    {
        name: 'hast-util-from-parse5@7.1.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-from-parse5'
    },
    {
        name: 'hast-util-parse-selector@3.1.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-parse-selector'
    },
    {
        name: 'hast-util-raw@7.2.3',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-raw'
    },
    {
        name: 'hast-util-to-html@8.0.4',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-to-html'
    },
    {
        name: 'hast-util-to-parse5@7.0.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-to-parse5'
    },
    {
        name: 'hast-util-whitespace@2.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hast-util-whitespace'
    },
    {
        name: 'hastscript@7.2.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/hastscript'
    },
    {
        name: 'hosted-git-info@2.8.9',
        license: 'ISC',
        url: 'https://github.com/npm/hosted-git-info'
    },
    {
        name: 'html-encoding-sniffer@3.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/html-encoding-sniffer'
    },
    {
        name: 'html-escaper@3.0.3',
        license: 'MIT',
        url: 'https://github.com/WebReflection/html-escaper'
    },
    {
        name: 'html-void-elements@2.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/html-void-elements'
    },
    {
        name: 'http-proxy-agent@5.0.0',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/node-http-proxy-agent'
    },
    {
        name: 'https-proxy-agent@5.0.1',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/node-https-proxy-agent'
    },
    {
        name: 'human-signals@3.0.1',
        license: 'Apache-2.0',
        url: 'https://github.com/ehmicky/human-signals'
    },
    {
        name: 'iconv-lite@0.4.24',
        license: 'MIT',
        url: 'https://github.com/ashtuchkin/iconv-lite'
    },
    {
        name: 'iconv-lite@0.6.3',
        license: 'MIT',
        url: 'https://github.com/ashtuchkin/iconv-lite'
    },
    {
        name: 'ieee754@1.2.1',
        license: 'BSD-3-Clause',
        url: 'https://github.com/feross/ieee754'
    },
    {
        name: 'ignore@5.2.4',
        license: 'MIT',
        url: 'https://github.com/kaelzhang/node-ignore'
    },
    {
        name: 'import-fresh@3.3.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/import-fresh'
    },
    {
        name: 'import-meta-resolve@2.2.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/import-meta-resolve'
    },
    {
        name: 'imurmurhash@0.1.4',
        license: 'MIT',
        url: 'https://github.com/jensyt/imurmurhash-js'
    },
    {
        name: 'inflight@1.0.6',
        license: 'ISC',
        url: 'https://github.com/npm/inflight'
    },
    {
        name: 'inherits@2.0.4',
        license: 'ISC',
        url: 'https://github.com/isaacs/inherits'
    },
    {
        name: 'inline-style-parser@0.1.1',
        license: 'MIT',
        url: 'https://github.com/remarkablemark/inline-style-parser'
    },
    {
        name: 'inquirer@9.1.4',
        license: 'MIT',
        url: 'https://github.com/SBoudrias/Inquirer.js'
    },
    {
        name: 'internal-slot@1.0.4',
        license: 'MIT',
        url: 'https://github.com/ljharb/internal-slot'
    },
    {
        name: 'is-array-buffer@3.0.1',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-array-buffer'
    },
    {
        name: 'is-bigint@1.0.4',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-bigint'
    },
    {
        name: 'is-binary-path@2.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-binary-path'
    },
    {
        name: 'is-boolean-object@1.1.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-boolean-object'
    },
    {
        name: 'is-buffer@2.0.5',
        license: 'MIT',
        url: 'https://github.com/feross/is-buffer'
    },
    {
        name: 'is-callable@1.2.7',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-callable'
    },
    {
        name: 'is-core-module@2.11.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-core-module'
    },
    {
        name: 'is-date-object@1.0.5',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-date-object'
    },
    {
        name: 'is-docker@2.2.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-docker'
    },
    {
        name: 'is-docker@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-docker'
    },
    {
        name: 'is-extendable@0.1.1',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/is-extendable'
    },
    {
        name: 'is-extglob@2.1.1',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/is-extglob'
    },
    {
        name: 'is-fullwidth-code-point@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-fullwidth-code-point'
    },
    {
        name: 'is-glob@4.0.3',
        license: 'MIT',
        url: 'https://github.com/micromatch/is-glob'
    },
    {
        name: 'is-interactive@2.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-interactive'
    },
    {
        name: 'is-negative-zero@2.0.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-negative-zero'
    },
    {
        name: 'is-number-object@1.0.7',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-number-object'
    },
    {
        name: 'is-number@7.0.0',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/is-number'
    },
    {
        name: 'is-path-inside@3.0.3',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-path-inside'
    },
    {
        name: 'is-plain-obj@4.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-plain-obj'
    },
    {
        name: 'is-potential-custom-element-name@1.0.1',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/is-potential-custom-element-name'
    },
    {
        name: 'is-regex@1.1.4',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-regex'
    },
    {
        name: 'is-shared-array-buffer@1.0.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-shared-array-buffer'
    },
    {
        name: 'is-stream@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-stream'
    },
    {
        name: 'is-string@1.0.7',
        license: 'MIT',
        url: 'https://github.com/ljharb/is-string'
    },
    {
        name: 'is-symbol@1.0.4',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-symbol'
    },
    {
        name: 'is-typed-array@1.1.10',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-typed-array'
    },
    {
        name: 'is-unicode-supported@1.3.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-unicode-supported'
    },
    {
        name: 'is-weakref@1.0.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/is-weakref'
    },
    {
        name: 'is-wsl@2.2.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/is-wsl'
    },
    {
        name: 'isexe@2.0.0',
        license: 'ISC',
        url: 'https://github.com/isaacs/isexe'
    },
    {
        name: 'js-sdsl@4.2.0',
        license: 'MIT',
        url: 'https://github.com/js-sdsl/js-sdsl'
    },
    {
        name: 'js-tokens@4.0.0',
        license: 'MIT',
        url: 'https://github.com/lydell/js-tokens'
    },
    {
        name: 'js-yaml@3.14.1',
        license: 'MIT',
        url: 'https://github.com/nodeca/js-yaml'
    },
    {
        name: 'js-yaml@4.1.0',
        license: 'MIT',
        url: 'https://github.com/nodeca/js-yaml'
    },
    {
        name: 'jsdom@21.1.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/jsdom'
    },
    {
        name: 'jsesc@2.5.2',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/jsesc'
    },
    {
        name: 'json-parse-even-better-errors@2.3.1',
        license: 'MIT',
        url: 'https://github.com/npm/json-parse-even-better-errors'
    },
    {
        name: 'json-schema-traverse@0.4.1',
        license: 'MIT',
        url: 'https://github.com/epoberezkin/json-schema-traverse'
    },
    {
        name: 'json-stable-stringify-without-jsonify@1.0.1',
        license: 'MIT',
        url: 'https://github.com/samn/json-stable-stringify'
    },
    {
        name: 'json5@2.2.3',
        license: 'MIT',
        url: 'https://github.com/json5/json5'
    },
    {
        name: 'jsonc-parser@2.3.1',
        license: 'MIT',
        url: 'https://github.com/microsoft/node-jsonc-parser'
    },
    {
        name: 'jsonc-parser@3.2.0',
        license: 'MIT',
        url: 'https://github.com/microsoft/node-jsonc-parser'
    },
    {
        name: 'jsx-ast-utils@3.3.3',
        license: 'MIT',
        url: 'https://github.com/jsx-eslint/jsx-ast-utils'
    },
    {
        name: 'kind-of@6.0.3',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/kind-of'
    },
    {
        name: 'kleur@3.0.3',
        license: 'MIT',
        url: 'https://github.com/lukeed/kleur'
    },
    {
        name: 'kleur@4.1.5',
        license: 'MIT',
        url: 'https://github.com/lukeed/kleur'
    },
    {
        name: 'levn@0.3.0',
        license: 'MIT',
        url: 'https://github.com/gkz/levn'
    },
    {
        name: 'levn@0.4.1',
        license: 'MIT',
        url: 'https://github.com/gkz/levn'
    },
    {
        name: 'license-checker@25.0.1',
        license: 'BSD-3-Clause',
        url: 'https://github.com/davglass/license-checker'
    },
    {
        name: 'lilconfig@2.0.6',
        license: 'MIT',
        url: 'https://github.com/antonk52/lilconfig'
    },
    {
        name: 'load-yaml-file@0.2.0',
        license: 'MIT',
        url: 'https://github.com/LinusU/load-yaml-file'
    },
    {
        name: 'locate-path@5.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/locate-path'
    },
    {
        name: 'locate-path@6.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/locate-path'
    },
    {
        name: 'lodash.merge@4.6.2',
        license: 'MIT',
        url: 'https://github.com/lodash/lodash'
    },
    {
        name: 'lodash@4.17.21',
        license: 'MIT',
        url: 'https://github.com/lodash/lodash'
    },
    {
        name: 'log-symbols@5.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/log-symbols'
    },
    {
        name: 'longest-streak@3.1.0',
        license: 'MIT',
        url: 'https://github.com/wooorm/longest-streak'
    },
    {
        name: 'loose-envify@1.4.0',
        license: 'MIT',
        url: 'https://github.com/zertosh/loose-envify'
    },
    {
        name: 'lru-cache@5.1.1',
        license: 'ISC',
        url: 'https://github.com/isaacs/node-lru-cache'
    },
    {
        name: 'lru-cache@6.0.0',
        license: 'ISC',
        url: 'https://github.com/isaacs/node-lru-cache'
    },
    {
        name: 'magic-string@0.27.0',
        license: 'MIT',
        url: 'https://github.com/rich-harris/magic-string'
    },
    {
        name: 'markdown-table@3.0.3',
        license: 'MIT',
        url: 'https://github.com/wooorm/markdown-table'
    },
    {
        name: 'mdast-util-definitions@5.1.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-definitions'
    },
    {
        name: 'mdast-util-find-and-replace@2.2.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-find-and-replace'
    },
    {
        name: 'mdast-util-from-markdown@1.2.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-from-markdown'
    },
    {
        name: 'mdast-util-gfm-autolink-literal@1.0.2',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm-autolink-literal'
    },
    {
        name: 'mdast-util-gfm-footnote@1.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm-footnote'
    },
    {
        name: 'mdast-util-gfm-strikethrough@1.0.2',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm-strikethrough'
    },
    {
        name: 'mdast-util-gfm-table@1.0.6',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm-table'
    },
    {
        name: 'mdast-util-gfm-task-list-item@1.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm-task-list-item'
    },
    {
        name: 'mdast-util-gfm@2.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-gfm'
    },
    {
        name: 'mdast-util-phrasing@3.0.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-phrasing'
    },
    {
        name: 'mdast-util-to-hast@12.2.5',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-to-hast'
    },
    {
        name: 'mdast-util-to-markdown@1.5.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-to-markdown'
    },
    {
        name: 'mdast-util-to-string@3.1.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/mdast-util-to-string'
    },
    {
        name: 'merge-stream@2.0.0',
        license: 'MIT',
        url: 'https://github.com/grncdr/merge-stream'
    },
    {
        name: 'merge2@1.4.1',
        license: 'MIT',
        url: 'https://github.com/teambition/merge2'
    },
    {
        name: 'micromark-core-commonmark@1.0.6',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-core-commonmark'
    },
    {
        name: 'micromark-extension-gfm-autolink-literal@1.0.3',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-autolink-literal'
    },
    {
        name: 'micromark-extension-gfm-footnote@1.0.4',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-footnote'
    },
    {
        name: 'micromark-extension-gfm-strikethrough@1.0.4',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-strikethrough'
    },
    {
        name: 'micromark-extension-gfm-table@1.0.5',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-table'
    },
    {
        name: 'micromark-extension-gfm-tagfilter@1.0.1',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-tagfilter'
    },
    {
        name: 'micromark-extension-gfm-task-list-item@1.0.3',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm-task-list-item'
    },
    {
        name: 'micromark-extension-gfm@2.0.1',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark-extension-gfm'
    },
    {
        name: 'micromark-factory-destination@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-factory-destination'
    },
    {
        name: 'micromark-factory-label@1.0.2',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-factory-label'
    },
    {
        name: 'micromark-factory-space@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-factory-space'
    },
    {
        name: 'micromark-factory-title@1.0.2',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-factory-title'
    },
    {
        name: 'micromark-factory-whitespace@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-factory-whitespace'
    },
    {
        name: 'micromark-util-character@1.1.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-character'
    },
    {
        name: 'micromark-util-chunked@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-chunked'
    },
    {
        name: 'micromark-util-classify-character@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-classify-character'
    },
    {
        name: 'micromark-util-combine-extensions@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-combine-extensions'
    },
    {
        name: 'micromark-util-decode-numeric-character-reference@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-decode-numeric-character-reference'
    },
    {
        name: 'micromark-util-decode-string@1.0.2',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-decode-string'
    },
    {
        name: 'micromark-util-encode@1.0.1',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-encode'
    },
    {
        name: 'micromark-util-html-tag-name@1.1.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-html-tag-name'
    },
    {
        name: 'micromark-util-normalize-identifier@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-normalize-identifier'
    },
    {
        name: 'micromark-util-resolve-all@1.0.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-resolve-all'
    },
    {
        name: 'micromark-util-sanitize-uri@1.1.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-sanitize-uri'
    },
    {
        name: 'micromark-util-subtokenize@1.0.2',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-subtokenize'
    },
    {
        name: 'micromark-util-symbol@1.0.1',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-symbol'
    },
    {
        name: 'micromark-util-types@1.0.2',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark-util-types'
    },
    {
        name: 'micromark@3.1.0',
        license: 'MIT',
        url: 'https://github.com/micromark/micromark/tree/main/packages/micromark'
    },
    {
        name: 'micromatch@4.0.5',
        license: 'MIT',
        url: 'https://github.com/micromatch/micromatch'
    },
    {
        name: 'mime-db@1.52.0',
        license: 'MIT',
        url: 'https://github.com/jshttp/mime-db'
    },
    {
        name: 'mime-types@2.1.35',
        license: 'MIT',
        url: 'https://github.com/jshttp/mime-types'
    },
    {
        name: 'mime@3.0.0',
        license: 'MIT',
        url: 'https://github.com/broofa/mime'
    },
    {
        name: 'mimic-fn@2.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/mimic-fn'
    },
    {
        name: 'mimic-fn@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/mimic-fn'
    },
    {
        name: 'minimatch@3.1.2',
        license: 'ISC',
        url: 'https://github.com/isaacs/minimatch'
    },
    {
        name: 'minimist@1.2.7',
        license: 'MIT',
        url: 'https://github.com/minimistjs/minimist'
    },
    {
        name: 'mkdirp@0.5.6',
        license: 'MIT',
        url: 'https://github.com/substack/node-mkdirp'
    },
    {
        name: 'mri@1.2.0',
        license: 'MIT',
        url: 'https://github.com/lukeed/mri'
    },
    {
        name: 'ms@2.1.2',
        license: 'MIT',
        url: 'https://github.com/zeit/ms'
    },
    {
        name: 'ms@2.1.3',
        license: 'MIT',
        url: 'https://github.com/vercel/ms'
    },
    {
        name: 'mute-stream@0.0.8',
        license: 'ISC',
        url: 'https://github.com/isaacs/mute-stream'
    },
    {
        name: 'nanoid@3.3.4',
        license: 'MIT',
        url: 'https://github.com/ai/nanoid'
    },
    {
        name: 'natural-compare-lite@1.4.0',
        license: 'MIT',
        url: 'https://github.com/litejs/natural-compare-lite'
    },
    {
        name: 'natural-compare@1.4.0',
        license: 'MIT',
        url: 'https://github.com/litejs/natural-compare-lite'
    },
    {
        name: 'nhdwebsite@0.0.1',
        license: 'UNLICENSED',
        url: 'https://github.com/'
    },
    {
        name: 'nlcst-to-string@3.1.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/nlcst-to-string'
    },
    {
        name: 'node-domexception@1.0.0',
        license: 'MIT',
        url: 'https://github.com/jimmywarting/node-domexception'
    },
    {
        name: 'node-fetch@3.3.0',
        license: 'MIT',
        url: 'https://github.com/node-fetch/node-fetch'
    },
    {
        name: 'node-releases@2.0.8',
        license: 'MIT',
        url: 'https://github.com/chicoxyzzy/node-releases'
    },
    {
        name: 'nopt@4.0.3',
        license: 'ISC',
        url: 'https://github.com/npm/nopt'
    },
    {
        name: 'normalize-package-data@2.5.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/npm/normalize-package-data'
    },
    {
        name: 'normalize-path@3.0.0',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/normalize-path'
    },
    {
        name: 'normalize-range@0.1.2',
        license: 'MIT',
        url: 'https://github.com/jamestalmage/normalize-range'
    },
    {
        name: 'npm-normalize-package-bin@1.0.1',
        license: 'ISC',
        url: 'https://github.com/npm/npm-normalize-package-bin'
    },
    {
        name: 'npm-run-path@5.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/npm-run-path'
    },
    {
        name: 'nwsapi@2.2.2',
        license: 'MIT',
        url: 'https://github.com/dperini/nwsapi'
    },
    {
        name: 'object-assign@4.1.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/object-assign'
    },
    {
        name: 'object-hash@3.0.0',
        license: 'MIT',
        url: 'https://github.com/puleos/object-hash'
    },
    {
        name: 'object-inspect@1.12.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/object-inspect'
    },
    {
        name: 'object-keys@1.1.1',
        license: 'MIT',
        url: 'https://github.com/ljharb/object-keys'
    },
    {
        name: 'object.assign@4.1.4',
        license: 'MIT',
        url: 'https://github.com/ljharb/object.assign'
    },
    {
        name: 'object.entries@1.1.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/Object.entries'
    },
    {
        name: 'object.fromentries@2.0.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/Object.fromEntries'
    },
    {
        name: 'object.hasown@1.1.2',
        license: 'MIT',
        url: 'https://github.com/es-shims/Object.hasOwn'
    },
    {
        name: 'object.values@1.1.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/Object.values'
    },
    {
        name: 'once@1.4.0',
        license: 'ISC',
        url: 'https://github.com/isaacs/once'
    },
    {
        name: 'onetime@5.1.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/onetime'
    },
    {
        name: 'onetime@6.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/onetime'
    },
    {
        name: 'open@8.4.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/open'
    },
    {
        name: 'optionator@0.8.3',
        license: 'MIT',
        url: 'https://github.com/gkz/optionator'
    },
    {
        name: 'optionator@0.9.1',
        license: 'MIT',
        url: 'https://github.com/gkz/optionator'
    },
    {
        name: 'ora@6.1.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/ora'
    },
    {
        name: 'os-homedir@1.0.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/os-homedir'
    },
    {
        name: 'os-tmpdir@1.0.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/os-tmpdir'
    },
    {
        name: 'osenv@0.1.5',
        license: 'ISC',
        url: 'https://github.com/npm/osenv'
    },
    {
        name: 'p-limit@2.3.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/p-limit'
    },
    {
        name: 'p-limit@3.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/p-limit'
    },
    {
        name: 'p-locate@4.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/p-locate'
    },
    {
        name: 'p-locate@5.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/p-locate'
    },
    {
        name: 'p-try@2.2.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/p-try'
    },
    {
        name: 'parent-module@1.0.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/parent-module'
    },
    {
        name: 'parse-latin@5.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/parse-latin'
    },
    {
        name: 'parse5@6.0.1',
        license: 'MIT',
        url: 'https://github.com/inikulin/parse5'
    },
    {
        name: 'parse5@7.1.2',
        license: 'MIT',
        url: 'https://github.com/inikulin/parse5'
    },
    {
        name: 'path-exists@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/path-exists'
    },
    {
        name: 'path-is-absolute@1.0.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/path-is-absolute'
    },
    {
        name: 'path-key@3.1.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/path-key'
    },
    {
        name: 'path-key@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/path-key'
    },
    {
        name: 'path-parse@1.0.7',
        license: 'MIT',
        url: 'https://github.com/jbgutierrez/path-parse'
    },
    {
        name: 'path-to-regexp@6.2.1',
        license: 'MIT',
        url: 'https://github.com/pillarjs/path-to-regexp'
    },
    {
        name: 'path-type@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/path-type'
    },
    {
        name: 'picocolors@1.0.0',
        license: 'ISC',
        url: 'https://github.com/alexeyraspopov/picocolors'
    },
    {
        name: 'picomatch@2.3.1',
        license: 'MIT',
        url: 'https://github.com/micromatch/picomatch'
    },
    {
        name: 'pify@2.3.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/pify'
    },
    {
        name: 'pify@4.0.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/pify'
    },
    {
        name: 'pkg-dir@4.2.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/pkg-dir'
    },
    {
        name: 'postcss-import@14.1.0',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-import'
    },
    {
        name: 'postcss-js@4.0.0',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-js'
    },
    {
        name: 'postcss-load-config@3.1.4',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-load-config'
    },
    {
        name: 'postcss-load-config@4.0.1',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-load-config'
    },
    {
        name: 'postcss-nested@6.0.0',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-nested'
    },
    {
        name: 'postcss-selector-parser@6.0.11',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss-selector-parser'
    },
    {
        name: 'postcss-value-parser@4.2.0',
        license: 'MIT',
        url: 'https://github.com/TrySound/postcss-value-parser'
    },
    {
        name: 'postcss@8.4.21',
        license: 'MIT',
        url: 'https://github.com/postcss/postcss'
    },
    {
        name: 'preferred-pm@3.0.3',
        license: 'MIT',
        url: 'https://github.com/zkochan/packages/tree/master/preferred-pm'
    },
    {
        name: 'prelude-ls@1.1.2',
        license: 'MIT',
        url: 'https://github.com/gkz/prelude-ls'
    },
    {
        name: 'prelude-ls@1.2.1',
        license: 'MIT',
        url: 'https://github.com/gkz/prelude-ls'
    },
    {
        name: 'prettier-linter-helpers@1.0.0',
        license: 'MIT',
        url: 'https://github.com/prettier/prettier-linter-helpers'
    },
    {
        name: 'prettier-plugin-astro@0.7.2',
        license: 'MIT',
        url: 'https://github.com/withastro/prettier-plugin-astro'
    },
    {
        name: 'prettier-plugin-tailwindcss@0.2.1',
        license: 'MIT',
        url: 'https://github.com/tailwindlabs/prettier-plugin-tailwindcss'
    },
    {
        name: 'prettier@2.8.2',
        license: 'MIT',
        url: 'https://github.com/prettier/prettier'
    },
    {
        name: 'prismjs@1.29.0',
        license: 'MIT',
        url: 'https://github.com/PrismJS/prism'
    },
    {
        name: 'prompts@2.4.2',
        license: 'MIT',
        url: 'https://github.com/terkelg/prompts'
    },
    {
        name: 'prop-types@15.8.1',
        license: 'MIT',
        url: 'https://github.com/facebook/prop-types'
    },
    {
        name: 'property-information@6.2.0',
        license: 'MIT',
        url: 'https://github.com/wooorm/property-information'
    },
    {
        name: 'psl@1.9.0',
        license: 'MIT',
        url: 'https://github.com/lupomontero/psl'
    },
    {
        name: 'punycode@2.2.0',
        license: 'MIT',
        url: 'https://github.com/bestiejs/punycode.js'
    },
    {
        name: 'punycode@2.3.0',
        license: 'MIT',
        url: 'https://github.com/mathiasbynens/punycode.js'
    },
    {
        name: 'querystringify@2.2.0',
        license: 'MIT',
        url: 'https://github.com/unshiftio/querystringify'
    },
    {
        name: 'queue-microtask@1.2.3',
        license: 'MIT',
        url: 'https://github.com/feross/queue-microtask'
    },
    {
        name: 'quick-lru@5.1.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/quick-lru'
    },
    {
        name: 'react-dom@18.2.0',
        license: 'MIT',
        url: 'https://github.com/facebook/react'
    },
    {
        name: 'react-is@16.13.1',
        license: 'MIT',
        url: 'https://github.com/facebook/react'
    },
    {
        name: 'react@18.2.0',
        license: 'MIT',
        url: 'https://github.com/facebook/react'
    },
    {
        name: 'read-cache@1.0.0',
        license: 'MIT',
        url: 'https://github.com/TrySound/read-cache'
    },
    {
        name: 'read-installed@4.0.3',
        license: 'ISC',
        url: 'https://github.com/isaacs/read-installed'
    },
    {
        name: 'read-package-json@2.1.2',
        license: 'ISC',
        url: 'https://github.com/npm/read-package-json'
    },
    {
        name: 'readable-stream@3.6.0',
        license: 'MIT',
        url: 'https://github.com/nodejs/readable-stream'
    },
    {
        name: 'readdir-scoped-modules@1.1.0',
        license: 'ISC',
        url: 'https://github.com/npm/readdir-scoped-modules'
    },
    {
        name: 'readdirp@3.6.0',
        license: 'MIT',
        url: 'https://github.com/paulmillr/readdirp'
    },
    {
        name: 'regexp.prototype.flags@1.4.3',
        license: 'MIT',
        url: 'https://github.com/es-shims/RegExp.prototype.flags'
    },
    {
        name: 'regexpp@3.2.0',
        license: 'MIT',
        url: 'https://github.com/mysticatea/regexpp'
    },
    {
        name: 'rehype-parse@8.0.4',
        license: 'MIT',
        url: 'https://github.com/rehypejs/rehype/tree/main/packages/rehype-parse'
    },
    {
        name: 'rehype-raw@6.1.1',
        license: 'MIT',
        url: 'https://github.com/rehypejs/rehype-raw'
    },
    {
        name: 'rehype-stringify@9.0.3',
        license: 'MIT',
        url: 'https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify'
    },
    {
        name: 'rehype@12.0.1',
        license: 'MIT',
        url: 'https://github.com/rehypejs/rehype/tree/main/packages/rehype'
    },
    {
        name: 'remark-gfm@3.0.1',
        license: 'MIT',
        url: 'https://github.com/remarkjs/remark-gfm'
    },
    {
        name: 'remark-parse@10.0.1',
        license: 'MIT',
        url: 'https://github.com/remarkjs/remark/tree/main/packages/remark-parse'
    },
    {
        name: 'remark-rehype@10.1.0',
        license: 'MIT',
        url: 'https://github.com/remarkjs/remark-rehype'
    },
    {
        name: 'remark-smartypants@2.0.0',
        license: 'MIT',
        url: 'https://github.com/silvenon/remark-smartypants'
    },
    {
        name: 'requires-port@1.0.0',
        license: 'MIT',
        url: 'https://github.com/unshiftio/requires-port'
    },
    {
        name: 'resolve-from@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/resolve-from'
    },
    {
        name: 'resolve@1.22.1',
        license: 'MIT',
        url: 'https://github.com/browserify/resolve'
    },
    {
        name: 'resolve@2.0.0-next.4',
        license: 'MIT',
        url: 'https://github.com/browserify/resolve'
    },
    {
        name: 'restore-cursor@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/restore-cursor'
    },
    {
        name: 'retext-latin@3.1.0',
        license: 'MIT',
        url: 'https://github.com/retextjs/retext/tree/main/packages/retext-latin'
    },
    {
        name: 'retext-smartypants@5.2.0',
        license: 'MIT',
        url: 'https://github.com/retextjs/retext-smartypants'
    },
    {
        name: 'retext-stringify@3.1.0',
        license: 'MIT',
        url: 'https://github.com/retextjs/retext/tree/main/packages/retext-stringify'
    },
    {
        name: 'retext@8.1.0',
        license: 'MIT',
        url: 'https://github.com/retextjs/retext/tree/main/packages/retext'
    },
    {
        name: 'reusify@1.0.4',
        license: 'MIT',
        url: 'https://github.com/mcollina/reusify'
    },
    {
        name: 'rimraf@3.0.2',
        license: 'ISC',
        url: 'https://github.com/isaacs/rimraf'
    },
    {
        name: 'rollup@3.12.1',
        license: 'MIT',
        url: 'https://github.com/rollup/rollup'
    },
    {
        name: 'run-async@2.4.1',
        license: 'MIT',
        url: 'https://github.com/SBoudrias/run-async'
    },
    {
        name: 'run-parallel@1.2.0',
        license: 'MIT',
        url: 'https://github.com/feross/run-parallel'
    },
    {
        name: 'rxjs@7.8.0',
        license: 'Apache-2.0',
        url: 'https://github.com/reactivex/rxjs'
    },
    {
        name: 's.color@0.0.15',
        license: 'MIT',
        url: 'https://github.com/TheRealSyler/s.color'
    },
    {
        name: 'sade@1.8.1',
        license: 'MIT',
        url: 'https://github.com/lukeed/sade'
    },
    {
        name: 'safe-buffer@5.2.1',
        license: 'MIT',
        url: 'https://github.com/feross/safe-buffer'
    },
    {
        name: 'safe-regex-test@1.0.0',
        license: 'MIT',
        url: 'https://github.com/ljharb/safe-regex-test'
    },
    {
        name: 'safer-buffer@2.1.2',
        license: 'MIT',
        url: 'https://github.com/ChALkeR/safer-buffer'
    },
    {
        name: 'sass-formatter@0.7.5',
        license: 'MIT',
        url: 'https://github.com/TheRealSyler/sass-formatter'
    },
    {
        name: 'saxes@6.0.0',
        license: 'ISC',
        url: 'https://github.com/lddubeau/saxes'
    },
    {
        name: 'scheduler@0.23.0',
        license: 'MIT',
        url: 'https://github.com/facebook/react'
    },
    {
        name: 'section-matter@1.0.0',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/section-matter'
    },
    {
        name: 'semver@5.7.1',
        license: 'ISC',
        url: 'https://github.com/npm/node-semver'
    },
    {
        name: 'semver@6.3.0',
        license: 'ISC',
        url: 'https://github.com/npm/node-semver'
    },
    {
        name: 'semver@7.3.8',
        license: 'ISC',
        url: 'https://github.com/npm/node-semver'
    },
    {
        name: 'server-destroy@1.0.1',
        license: 'ISC',
        url: 'https://github.com/isaacs/server-destroy'
    },
    {
        name: 'set-cookie-parser@2.5.1',
        license: 'MIT',
        url: 'https://github.com/nfriedly/set-cookie-parser'
    },
    {
        name: 'shebang-command@2.0.0',
        license: 'MIT',
        url: 'https://github.com/kevva/shebang-command'
    },
    {
        name: 'shebang-regex@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/shebang-regex'
    },
    {
        name: 'shiki@0.11.1',
        license: 'MIT',
        url: 'https://github.com/octref/shiki'
    },
    {
        name: 'side-channel@1.0.4',
        license: 'MIT',
        url: 'https://github.com/ljharb/side-channel'
    },
    {
        name: 'signal-exit@3.0.7',
        license: 'ISC',
        url: 'https://github.com/tapjs/signal-exit'
    },
    {
        name: 'sisteransi@1.0.5',
        license: 'MIT',
        url: 'https://github.com/terkelg/sisteransi'
    },
    {
        name: 'slash@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/slash'
    },
    {
        name: 'slash@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/slash'
    },
    {
        name: 'slide@1.1.6',
        license: 'ISC',
        url: 'https://github.com/isaacs/slide-flow-control'
    },
    {
        name: 'source-map-js@1.0.2',
        license: 'BSD-3-Clause',
        url: 'https://github.com/7rulnik/source-map-js'
    },
    {
        name: 'source-map@0.6.1',
        license: 'BSD-3-Clause',
        url: 'https://github.com/mozilla/source-map'
    },
    {
        name: 'source-map@0.7.4',
        license: 'BSD-3-Clause',
        url: 'https://github.com/mozilla/source-map'
    },
    {
        name: 'space-separated-tokens@2.0.2',
        license: 'MIT',
        url: 'https://github.com/wooorm/space-separated-tokens'
    },
    {
        name: 'spdx-compare@1.0.0',
        license: 'MIT',
        url: 'https://github.com/kemitchell/spdx-compare.js'
    },
    {
        name: 'spdx-correct@3.1.1',
        license: 'Apache-2.0',
        url: 'https://github.com/jslicense/spdx-correct.js'
    },
    {
        name: 'spdx-exceptions@2.3.0',
        license: 'CC-BY-3.0',
        url: 'https://github.com/kemitchell/spdx-exceptions.json'
    },
    {
        name: 'spdx-expression-parse@3.0.1',
        license: 'MIT',
        url: 'https://github.com/jslicense/spdx-expression-parse.js'
    },
    {
        name: 'spdx-license-ids@3.0.12',
        license: 'CC0-1.0',
        url: 'https://github.com/jslicense/spdx-license-ids'
    },
    {
        name: 'spdx-ranges@2.1.1',
        license: '(MIT AND CC-BY-3.0)',
        url: 'https://github.com/kemitchell/spdx-ranges.js'
    },
    {
        name: 'spdx-satisfies@4.0.1',
        license: 'MIT',
        url: 'https://github.com/kemitchell/spdx-satisfies.js'
    },
    {
        name: 'sprintf-js@1.0.3',
        license: 'BSD-3-Clause',
        url: 'https://github.com/alexei/sprintf.js'
    },
    {
        name: 'streamsearch@1.1.0',
        license: 'MIT',
        url: 'https://github.com/mscdex/streamsearch'
    },
    {
        name: 'string-width@4.2.3',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/string-width'
    },
    {
        name: 'string-width@5.1.2',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/string-width'
    },
    {
        name: 'string.prototype.matchall@4.0.8',
        license: 'MIT',
        url: 'https://github.com/es-shims/String.prototype.matchAll'
    },
    {
        name: 'string.prototype.trimend@1.0.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/String.prototype.trimEnd'
    },
    {
        name: 'string.prototype.trimstart@1.0.6',
        license: 'MIT',
        url: 'https://github.com/es-shims/String.prototype.trimStart'
    },
    {
        name: 'string_decoder@1.3.0',
        license: 'MIT',
        url: 'https://github.com/nodejs/string_decoder'
    },
    {
        name: 'stringify-entities@4.0.3',
        license: 'MIT',
        url: 'https://github.com/wooorm/stringify-entities'
    },
    {
        name: 'strip-ansi@6.0.1',
        license: 'MIT',
        url: 'https://github.com/chalk/strip-ansi'
    },
    {
        name: 'strip-ansi@7.0.1',
        license: 'MIT',
        url: 'https://github.com/chalk/strip-ansi'
    },
    {
        name: 'strip-bom-string@1.0.0',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/strip-bom-string'
    },
    {
        name: 'strip-bom@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/strip-bom'
    },
    {
        name: 'strip-bom@4.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/strip-bom'
    },
    {
        name: 'strip-final-newline@3.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/strip-final-newline'
    },
    {
        name: 'strip-json-comments@3.1.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/strip-json-comments'
    },
    {
        name: 'style-to-object@0.3.0',
        license: 'MIT',
        url: 'https://github.com/remarkablemark/style-to-object'
    },
    {
        name: 'suf-log@2.5.3',
        license: 'MIT',
        url: 'https://github.com/TheRealSyler/suf-log'
    },
    {
        name: 'supports-color@5.5.0',
        license: 'MIT',
        url: 'https://github.com/chalk/supports-color'
    },
    {
        name: 'supports-color@7.2.0',
        license: 'MIT',
        url: 'https://github.com/chalk/supports-color'
    },
    {
        name: 'supports-esm@1.0.0',
        license: 'MIT',
        url: 'https://github.com/targos/supports-esm'
    },
    {
        name: 'supports-preserve-symlinks-flag@1.0.0',
        license: 'MIT',
        url: 'https://github.com/inspect-js/node-supports-preserve-symlinks-flag'
    },
    {
        name: 'symbol-tree@3.2.4',
        license: 'MIT',
        url: 'https://github.com/jsdom/js-symbol-tree'
    },
    {
        name: 'synckit@0.8.4',
        license: 'MIT',
        url: 'https://github.com/un-ts/synckit'
    },
    {
        name: 'tailwind-gradient-mask-image@1.0.0',
        license: 'MIT',
        url: 'https://github.com/juhanakristian/tailwind-gradient-mask-image'
    },
    {
        name: 'tailwindcss@3.2.4',
        license: 'MIT',
        url: 'https://github.com/tailwindlabs/tailwindcss'
    },
    {
        name: 'text-table@0.2.0',
        license: 'MIT',
        url: 'https://github.com/substack/text-table'
    },
    {
        name: 'through@2.3.8',
        license: 'MIT',
        url: 'https://github.com/dominictarr/through'
    },
    {
        name: 'tiny-glob@0.2.9',
        license: 'MIT',
        url: 'https://github.com/terkelg/tiny-glob'
    },
    {
        name: 'tmp@0.0.33',
        license: 'MIT',
        url: 'https://github.com/raszi/node-tmp'
    },
    {
        name: 'to-fast-properties@2.0.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/to-fast-properties'
    },
    {
        name: 'to-regex-range@5.0.1',
        license: 'MIT',
        url: 'https://github.com/micromatch/to-regex-range'
    },
    {
        name: 'tough-cookie@4.1.2',
        license: 'BSD-3-Clause',
        url: 'https://github.com/salesforce/tough-cookie'
    },
    {
        name: 'tr46@3.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/tr46'
    },
    {
        name: 'treeify@1.1.0',
        license: 'MIT',
        url: 'https://github.com/notatestuser/treeify'
    },
    {
        name: 'trim-lines@3.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/trim-lines'
    },
    {
        name: 'trough@2.1.0',
        license: 'MIT',
        url: 'https://github.com/wooorm/trough'
    },
    {
        name: 'tsconfig-resolver@3.0.1',
        license: 'MIT',
        url: 'https://github.com/'
    },
    {
        name: 'tslib@1.14.1',
        license: '0BSD',
        url: 'https://github.com/Microsoft/tslib'
    },
    {
        name: 'tslib@2.4.1',
        license: '0BSD',
        url: 'https://github.com/Microsoft/tslib'
    },
    {
        name: 'tslib@2.5.0',
        license: '0BSD',
        url: 'https://github.com/Microsoft/tslib'
    },
    {
        name: 'tsutils@3.21.0',
        license: 'MIT',
        url: 'https://github.com/ajafff/tsutils'
    },
    {
        name: 'type-check@0.3.2',
        license: 'MIT',
        url: 'https://github.com/gkz/type-check'
    },
    {
        name: 'type-check@0.4.0',
        license: 'MIT',
        url: 'https://github.com/gkz/type-check'
    },
    {
        name: 'type-fest@0.13.1',
        license: '(MIT OR CC0-1.0)',
        url: 'https://github.com/sindresorhus/type-fest'
    },
    {
        name: 'type-fest@0.20.2',
        license: '(MIT OR CC0-1.0)',
        url: 'https://github.com/sindresorhus/type-fest'
    },
    {
        name: 'type-fest@2.19.0',
        license: '(MIT OR CC0-1.0)',
        url: 'https://github.com/sindresorhus/type-fest'
    },
    {
        name: 'type-fest@3.5.4',
        license: '(MIT OR CC0-1.0)',
        url: 'https://github.com/sindresorhus/type-fest'
    },
    {
        name: 'typed-array-length@1.0.4',
        license: 'MIT',
        url: 'https://github.com/inspect-js/typed-array-length'
    },
    {
        name: 'typescript@4.9.4',
        license: 'Apache-2.0',
        url: 'https://github.com/Microsoft/TypeScript'
    },
    {
        name: 'unbox-primitive@1.0.2',
        license: 'MIT',
        url: 'https://github.com/ljharb/unbox-primitive'
    },
    {
        name: 'undici@5.16.0',
        license: 'MIT',
        url: 'https://github.com/nodejs/undici'
    },
    {
        name: 'unherit@3.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/unherit'
    },
    {
        name: 'unified@10.1.2',
        license: 'MIT',
        url: 'https://github.com/unifiedjs/unified'
    },
    {
        name: 'unist-builder@3.0.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-builder'
    },
    {
        name: 'unist-util-generated@2.0.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-generated'
    },
    {
        name: 'unist-util-is@5.1.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-is'
    },
    {
        name: 'unist-util-modify-children@3.1.0',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-modify-children'
    },
    {
        name: 'unist-util-position@4.0.3',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-position'
    },
    {
        name: 'unist-util-stringify-position@3.0.2',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-stringify-position'
    },
    {
        name: 'unist-util-visit-children@2.0.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-visit-children'
    },
    {
        name: 'unist-util-visit-parents@5.1.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-visit-parents'
    },
    {
        name: 'unist-util-visit@4.1.1',
        license: 'MIT',
        url: 'https://github.com/syntax-tree/unist-util-visit'
    },
    {
        name: 'universalify@0.2.0',
        license: 'MIT',
        url: 'https://github.com/RyanZim/universalify'
    },
    {
        name: 'update-browserslist-db@1.0.10',
        license: 'MIT',
        url: 'https://github.com/browserslist/update-db'
    },
    {
        name: 'uri-js@4.4.1',
        license: 'BSD-2-Clause',
        url: 'https://github.com/garycourt/uri-js'
    },
    {
        name: 'url-parse@1.5.10',
        license: 'MIT',
        url: 'https://github.com/unshiftio/url-parse'
    },
    {
        name: 'util-deprecate@1.0.2',
        license: 'MIT',
        url: 'https://github.com/TooTallNate/util-deprecate'
    },
    {
        name: 'util-extend@1.0.3',
        license: 'MIT',
        url: 'https://github.com/isaacs/util-extend'
    },
    {
        name: 'uvu@0.5.6',
        license: 'MIT',
        url: 'https://github.com/lukeed/uvu'
    },
    {
        name: 'validate-npm-package-license@3.0.4',
        license: 'Apache-2.0',
        url: 'https://github.com/kemitchell/validate-npm-package-license.js'
    },
    {
        name: 'vfile-location@4.0.1',
        license: 'MIT',
        url: 'https://github.com/vfile/vfile-location'
    },
    {
        name: 'vfile-message@3.1.3',
        license: 'MIT',
        url: 'https://github.com/vfile/vfile-message'
    },
    {
        name: 'vfile@5.3.6',
        license: 'MIT',
        url: 'https://github.com/vfile/vfile'
    },
    {
        name: 'vite@4.0.4',
        license: 'MIT',
        url: 'https://github.com/vitejs/vite'
    },
    {
        name: 'vitefu@0.2.4',
        license: 'MIT',
        url: 'https://github.com/svitejs/vitefu'
    },
    {
        name: 'vscode-css-languageservice@6.2.1',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-css-languageservice'
    },
    {
        name: 'vscode-html-languageservice@5.0.3',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-html-languageservice'
    },
    {
        name: 'vscode-jsonrpc@8.0.2',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-languageserver-node'
    },
    {
        name: 'vscode-languageserver-protocol@3.17.2',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-languageserver-node'
    },
    {
        name: 'vscode-languageserver-textdocument@1.0.8',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-languageserver-node'
    },
    {
        name: 'vscode-languageserver-types@3.17.2',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-languageserver-node'
    },
    {
        name: 'vscode-languageserver@8.0.2',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-languageserver-node'
    },
    {
        name: 'vscode-oniguruma@1.7.0',
        license: 'MIT',
        url: 'https://github.com/microsoft/vscode-oniguruma'
    },
    {
        name: 'vscode-textmate@6.0.0',
        license: 'MIT',
        url: 'https://github.com/microsoft/vscode-textmate'
    },
    {
        name: 'vscode-uri@2.1.2',
        license: 'MIT',
        url: 'https://github.com/Microsoft/vscode-uri'
    },
    {
        name: 'vscode-uri@3.0.7',
        license: 'MIT',
        url: 'https://github.com/microsoft/vscode-uri'
    },
    {
        name: 'w3c-xmlserializer@4.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/w3c-xmlserializer'
    },
    {
        name: 'wcwidth@1.0.1',
        license: 'MIT',
        url: 'https://github.com/timoxley/wcwidth'
    },
    {
        name: 'web-namespaces@2.0.1',
        license: 'MIT',
        url: 'https://github.com/wooorm/web-namespaces'
    },
    {
        name: 'web-streams-polyfill@3.2.1',
        license: 'MIT',
        url: 'https://github.com/MattiasBuelens/web-streams-polyfill'
    },
    {
        name: 'webidl-conversions@7.0.0',
        license: 'BSD-2-Clause',
        url: 'https://github.com/jsdom/webidl-conversions'
    },
    {
        name: 'whatwg-encoding@2.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/whatwg-encoding'
    },
    {
        name: 'whatwg-mimetype@3.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/whatwg-mimetype'
    },
    {
        name: 'whatwg-url@11.0.0',
        license: 'MIT',
        url: 'https://github.com/jsdom/whatwg-url'
    },
    {
        name: 'which-boxed-primitive@1.0.2',
        license: 'MIT',
        url: 'https://github.com/inspect-js/which-boxed-primitive'
    },
    {
        name: 'which-pm-runs@1.1.0',
        license: 'MIT',
        url: 'https://github.com/zkochan/packages/tree/main/which-pm-runs'
    },
    {
        name: 'which-pm@2.0.0',
        license: 'MIT',
        url: 'https://github.com/zkochan/packages/tree/master/which-pm'
    },
    {
        name: 'which-typed-array@1.1.9',
        license: 'MIT',
        url: 'https://github.com/inspect-js/which-typed-array'
    },
    {
        name: 'which@2.0.2',
        license: 'ISC',
        url: 'https://github.com/isaacs/node-which'
    },
    {
        name: 'widest-line@4.0.1',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/widest-line'
    },
    {
        name: 'word-wrap@1.2.3',
        license: 'MIT',
        url: 'https://github.com/jonschlinkert/word-wrap'
    },
    {
        name: 'wrap-ansi@8.0.1',
        license: 'MIT',
        url: 'https://github.com/chalk/wrap-ansi'
    },
    {
        name: 'wrappy@1.0.2',
        license: 'ISC',
        url: 'https://github.com/npm/wrappy'
    },
    {
        name: 'ws@8.12.0',
        license: 'MIT',
        url: 'https://github.com/websockets/ws'
    },
    {
        name: 'xml-escape@1.1.0',
        license: 'MIT*',
        url: 'https://github.com/miketheprogrammer/xml-escape'
    },
    {
        name: 'xml-name-validator@4.0.0',
        license: 'Apache-2.0',
        url: 'https://github.com/jsdom/xml-name-validator'
    },
    {
        name: 'xmlchars@2.2.0',
        license: 'MIT',
        url: 'https://github.com/lddubeau/xmlchars'
    },
    {
        name: 'xtend@4.0.2',
        license: 'MIT',
        url: 'https://github.com/Raynos/xtend'
    },
    {
        name: 'yallist@3.1.1',
        license: 'ISC',
        url: 'https://github.com/isaacs/yallist'
    },
    {
        name: 'yallist@4.0.0',
        license: 'ISC',
        url: 'https://github.com/isaacs/yallist'
    },
    {
        name: 'yaml@1.10.2',
        license: 'ISC',
        url: 'https://github.com/eemeli/yaml'
    },
    {
        name: 'yaml@2.2.1',
        license: 'ISC',
        url: 'https://github.com/eemeli/yaml'
    },
    {
        name: 'yargs-parser@21.1.1',
        license: 'ISC',
        url: 'https://github.com/yargs/yargs-parser'
    },
    {
        name: 'yocto-queue@0.1.0',
        license: 'MIT',
        url: 'https://github.com/sindresorhus/yocto-queue'
    },
    {
        name: 'zod@3.20.2',
        license: 'MIT',
        url: 'https://github.com/colinhacks/zod'
    },
    {
        name: 'zwitch@2.0.4',
        license: 'MIT',
        url: 'https://github.com/wooorm/zwitch'
    }
];
