// Path: src/utils/env.tsx
// This file is automatically generated by scripts/env.tsx
// Do not edit this file manually, it will be overwritten

interface SiteEnv {
    target: 'nhd' | 'gh';
    ghLiveUrl: string;
}

export const env: SiteEnv = {
    "target": "nhd",
    "ghLiveUrl": "https://JoshuaBrest.github.io/nhd2022-23"
};
