// Path: src/utils/siteEnv.tsx
// This file is automatically generated by scripts/siteEnv.js
// Do not edit this file manually, it will be overwritten

interface SiteEnv {
    target: 'nhd' | 'gh';
    ghLiveUrl: string;
}

export const env: SiteEnv = {
    target: 'nhd',
    ghLiveUrl: 'https://joshuabrest.github.io/nhd2022-23'
};
