import checker from 'license-checker';
import path from 'node:path';
import fs from 'node:fs';

const main = async () => {
    // Get the license information
    const licenses = await new Promise((resolve, reject) => {
        checker.init(
            {
                start: process.cwd()
            },
            (err, data) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(data);
                }
            }
        );
    });

    // Detect files outside npm packages
    const overrides = fs.readFileSync(
        path.join(process.cwd(), 'overrides.json'),
        'utf8'
    );

    // Parse json
    const overridesJson = JSON.parse(overrides);

    // Get the licenses
    const licensesJson = Object.keys(licenses).map((key) => {
        return {
            name: key,
            license: licenses[key].licenses,
            url: licenses[key].repository ?? 'https://github.com/'
        };
    });

    // Get the overrides
    const overridesJsonKeys = Object.values(overridesJson);

    // Combine the licenses and overrides
    const combined = [...overridesJsonKeys, ...licensesJson];

    // Create the tsx file
    const tsx = `// Path: src/utils/attributions.tsx
// This file is automatically generated by scripts/attributions.tsx
// Do not edit this file manually, it will be overwritten

export const attributions = ${JSON.stringify(combined, null, '    ')};
`;

    // Write the file
    fs.writeFileSync(
        path.join(process.cwd(), 'src/utils/attributions.tsx'),
        tsx
    );

    // Log the success
    console.log('ok');
};

main();
