import dotenv from 'dotenv';
import path from 'node:path';
import fs from 'node:fs';

dotenv.config();

const main = async () => {
    // Get the env information
    const env = {
        target: process.env.IS_NHD_TARGET === 'true' ? 'nhd' : 'gh',
        ghLiveUrl: `https://${process.env.GH_OWNER}.github.io/${process.env.GH_REPO}`
    };

    // Create the tsx file
    const tsx = `// Path: src/utils/env.tsx
// This file is automatically generated by scripts/env.tsx
// Do not edit this file manually, it will be overwritten

interface SiteEnv {
    target: 'nhd' | 'gh';
    ghLiveUrl: string;
}

export const env: SiteEnv = ${JSON.stringify(env, null, '    ')};
`;

    // Write the file
    fs.writeFileSync(path.join(process.cwd(), 'src/utils/env.tsx'), tsx);

    // Log the success
    console.log('ok');
};

main();
